.TH factor 1 "12 Apr. 2012"
.SH NAME
\fBfactor\fR \- print the prime factors of integer
.SH SYNOPSIS
\fBfactor [ [ \-\-raw ] [ \-\-linebreak ] [ \-\-threads=\fINUMBER\fB ] \fINUMBER\fB [ \fINUMBER\fB ... ] | \-\-benchmark | \-\-version | \-\-help ]
.SH DESCRIPTION
print the prime factors of each specified \fINUMBER\fR; if none are specified, read them from standard input
.P
each \fINUMBER\fR must be a non-negative integer less than \fB2^64\fR
.SH OPTIONS
\fB\-\-raw, \-r\fR \- print prime factors in raw format (\fIb\fR times instead of form \fIp\fR \fB^\fR \fIb\fR)
.P
\fB\-\-linebreak, \-n\fR \- print prime factors on separate lines
.P
\fB\-\-threads=\fINUMBER\fB, \-j \fINUMBER\fR \- split into \fINUMBER\fR threads (number of processors by default); if \fINUMBER\fB = 0\fR, number of threads is unlimited
.P
\fB\-\-benchmark\fR \- print some useful benchmarks and exit
.P
\fB\-\-version, \-v\fR \- print version and exit
.P
\fB\-\-help, \-h\fR \- print help message and exit
.SH SEE ALSO
\fB factor\fR(3)
.SH AUTHOR
Nikita Vaganov
